apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
  labels:
    app: notification-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      containers:
        - name: notification-service
          image: stacksimplify/kube-notifications-microservice:3.0.0-AWS-XRay
          ports:
            - containerPort: 8096
          imagePullPolicy: Always
          env:
            - name: AWS_MAIL_SERVER_HOST
              value: "smtp-service"
            - name: AWS_MAIL_SERVER_USERNAME
              value: "AKIAZUQG4EA3JV7O3ZHP"
            - name: AWS_MAIL_SERVER_PASSWORD
              value: "BKKyVJyrVIbzSpZ6GvRuWckXdeGKHh1A1S9lfjIovpXf"
            - name: AWS_MAIL_SERVER_FROM_ADDRESS
              value: "kartimothy@gmail.com"